### ISSUE TITLE
No symbol named `global-set-key'

### ISSUE THREAD

**Issue by NalaGinrut** [spk121/zile#1]
I run zile-on-guile successfully on guile-2.2 with patches from me (I may send them later).
But it complains a warning:

zile.scm:129:2: warning: possibly unbound variable `global-set-key'

I think `global-set-key' is in Emacs, I never saw it in Guile. Should we implement it? 
@spk121

**Comment by spk121** [comment]
There is a global-set-key in emacs.  But, I think the problem is that bind.c's "set-key" should have been exported as "global-set-key", instead of "set-key".

**Comment by NalaGinrut** [comment]
ok, do you need patch for this issue? And I have other patch to make it work for the latest guile, since something was obsoleted out. I can send them all.

**Comment by amirouche** [comment]
@NalaGinrut please make a PR!

**Comment by spk121** [comment]
@NalaGinrut I'd be happy to pull in any patches you have.  Otherwise, I'll fix it, but, not this week.

**Comment by NalaGinrut** [comment]
I failed to find a way to export global-set-key properly. It seems that all symbols in the elf need to export to Guile environment, usually there'd be dynamic-call. But I've no idea how to export symbols from a elf file rather than .so

**Comment by spk121** [comment]
I think this is fixed in 1ac5832bad4f50d7d79b70686f22b9205a7cf7ac
